# Generated by Django 3.2.4 on 2021-10-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('project_name', models.CharField(max_length=256)),
                ('deadline', models.DateTimeField()),
                ('describe', models.TextField(max_length=10000)),
                ('progress', models.IntegerField(default=0)),
                ('design_confirm', models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default='Không', max_length=10)),
                ('design_file', models.FileField(upload_to=project.models.user_directory_path)),
                ('payment_status', models.CharField(choices=[('Đã đặt cọc', 'Đã đặt cọc'), ('Chờ đặt cọc', 'Chờ đặt cọc'), ('Đã thanh toán', 'Đã thanh toán'), ('Chờ thanh toán', 'Chờ thanh toán')], default='Chờ đặt cọc', max_length=50)),
                ('change_time', models.IntegerField(default=0, editable=False)),
                ('rules_agree', models.CharField(choices=[('Đồng ý', 'Đã đồng ý điều khoản'), ('Chưa đồng ý', 'Chưa đồng ý điều khoản')], default='Chưa đồng ý', max_length=30)),
                ('majors', models.ManyToManyField(to='project.Major')),
            ],
            options={
                'ordering': ['-created_date', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('deadline', models.DateTimeField()),
                ('describe', models.TextField(max_length=10000)),
                ('design_confirm', models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], default='Không', max_length=10)),
                ('design_file', models.FileField(upload_to=project.models.user_directory_path)),
                ('change_date', models.DateField(editable=False)),
                ('change_order', models.IntegerField(editable=False)),
                ('majors', models.ManyToManyField(to='project.Major')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='project.project')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projecttype')),
            ],
            options={
                'ordering': ['project', '-change_date', '-change_order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.projecttype'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
