# Generated by Django 3.2.4 on 2021-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='international',
            field=models.BooleanField(default=False),
        ),
    ]
