# Generated by Django 3.2.4 on 2021-11-03 18:19

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_bank_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_project_file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.project_user_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to=project.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
