# Generated by Django 3.2.4 on 2021-10-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
