# Generated by Django 3.2.4 on 2021-10-25 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_bank_international'),
        ('vnpay', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(default='NCB', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='project.bank'),
            preserve_default=False,
        ),
    ]
